In [1]:
import pandas as pd

In [2]:
../

SyntaxError: invalid syntax (3509093073.py, line 1)

In [3]:
df_songs = pd.read_excel('../data/raw/Sony Music Publishing (SCORE)/SCORE_Song_Summary.xlsx', header = 7)

In [4]:
df_songs

                 Song Title          Unnamed: 1 Client Royalty
0                        +5                 NaN           7.96
1    1 XANNY GEHT NOCH KLAR                 NaN           2.26
2                    ??????                 NaN           0.04
3                     AGAIN                 NaN          132.9
4                     AMORE                 NaN          83.87
..                      ...                 ...            ...
112               WUSYANAME                 NaN         157.47
113                ZOR DEIL                 NaN           0.59
114                     NaN  Domestic Earnings:      34,450.04
115                     NaN   Foreign Earnings:       7,357.58
116                     NaN     Total Earnings:      41,807.62

[117 rows x 3 columns]

In [5]:
df_songs = df_songs.dropna(subset=['Song Title'])

In [6]:
df_songs

                 Song Title Unnamed: 1 Client Royalty
0                        +5        NaN           7.96
1    1 XANNY GEHT NOCH KLAR        NaN           2.26
2                    ??????        NaN           0.04
3                     AGAIN        NaN          132.9
4                     AMORE        NaN          83.87
..                      ...        ...            ...
109       WHERE YOU BEEN AT        NaN          28.63
110            WHO IS MELO?        NaN          72.52
111              WTF I WANT        NaN          89.47
112               WUSYANAME        NaN         157.47
113                ZOR DEIL        NaN           0.59

[114 rows x 3 columns]

In [7]:
df_songs = df_songs.drop(columns=['Unnamed: 1'])

In [8]:
df_songs

                 Song Title Client Royalty
0                        +5           7.96
1    1 XANNY GEHT NOCH KLAR           2.26
2                    ??????           0.04
3                     AGAIN          132.9
4                     AMORE          83.87
..                      ...            ...
109       WHERE YOU BEEN AT          28.63
110            WHO IS MELO?          72.52
111              WTF I WANT          89.47
112               WUSYANAME         157.47
113                ZOR DEIL           0.59

[114 rows x 2 columns]

In [9]:
df_parties = pd.read_excel('../data/raw/Sony Music Publishing (SCORE)/SCORE_Song_Interested_Parties.xlsx', header = 5)

In [10]:
df_parties

,Song,Song Title,Writer(s)
0,6565950,+5,"Amiranovich Amiranovich(50%), Leonardo Bostan(..."
1,6547320,1 Xanny geht noch klar,"Kewin Rewers(50%), Leonardo Bostan(50%)"
2,5992541,2 Cocky,"Leonardo Bostan(50%), Luis Gaerdes(50%)"
3,6572314,??????,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost..."
4,6588723,AMORE,"Elvis M(50%), Leonardo Bostan(50%)"
...,...,...,...
123,6207402,Za Smokin,"Angelo Turpin Jr(50%), Leonardo Bostan(50%)"
124,7172291,Zor Deil,"Alp Mutlu(16.60%), Emir Oztaskin(16.70%), Ferh..."
125,6602114,film,Leonardo Bostan(100%)
126,7019464,short & SWEET (feat. Baby Money & Payroll Giov...,"Carlos Deshawn Fischer(12.50%), Dior Giovanni ..."
127,6594683,track,"Leonardo Bostan(50%), Zen C(50%)"

In [11]:
df_songs['Song Title'] = df_songs['Song Title'].str.strip().str.upper()
df_parties['Song Title'] = df_parties['Song Title'].str.strip().str.upper()

In [12]:
df = pd.merge(df_songs, df_parties, on='Song Title', how='outer')

In [13]:
df

,Song Title,Client Royalty,Song,Writer(s)
0,+5,7.96,6565950,"Amiranovich Amiranovich(50%), Leonardo Bostan(..."
1,1 XANNY GEHT NOCH KLAR,2.26,6547320,"Kewin Rewers(50%), Leonardo Bostan(50%)"
2,2 COCKY,NaN,5992541,"Leonardo Bostan(50%), Luis Gaerdes(50%)"
3,??????,0.04,6572314,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost..."
4,AGAIN,132.9,6537410,"Jairmy Long(50%), Leonardo Bostan(12.50%), Max..."
...,...,...,...,...
123,WHO IS MELO?,72.52,6547321,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost..."
124,WTF I WANT,89.47,6972662,"Leonardo Bostan(12.50%), Martin Mccurtis(25%),..."
125,WUSYANAME,157.47,6685283,"Klayd Klayd(30%), Leonardo Bostan(70%)"
126,ZA SMOKIN,NaN,6207402,"Angelo Turpin Jr(50%), Leonardo Bostan(50%)"
127,ZOR DEIL,0.59,7172291,"Alp Mutlu(16.60%), Emir Oztaskin(16.70%), Ferh..."

In [14]:
df = df.rename(columns={'Song': 'song_id', 'Song Title': 'song_title', 'Client Royalty': 'my_earnings_usd', 'Writer(s)': 'writers'})

In [15]:
df

,song_title,my_earnings_usd,song_id,writers
0,+5,7.96,6565950,"Amiranovich Amiranovich(50%), Leonardo Bostan(..."
1,1 XANNY GEHT NOCH KLAR,2.26,6547320,"Kewin Rewers(50%), Leonardo Bostan(50%)"
2,2 COCKY,NaN,5992541,"Leonardo Bostan(50%), Luis Gaerdes(50%)"
3,??????,0.04,6572314,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost..."
4,AGAIN,132.9,6537410,"Jairmy Long(50%), Leonardo Bostan(12.50%), Max..."
...,...,...,...,...
123,WHO IS MELO?,72.52,6547321,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost..."
124,WTF I WANT,89.47,6972662,"Leonardo Bostan(12.50%), Martin Mccurtis(25%),..."
125,WUSYANAME,157.47,6685283,"Klayd Klayd(30%), Leonardo Bostan(70%)"
126,ZA SMOKIN,NaN,6207402,"Angelo Turpin Jr(50%), Leonardo Bostan(50%)"
127,ZOR DEIL,0.59,7172291,"Alp Mutlu(16.60%), Emir Oztaskin(16.70%), Ferh..."

In [16]:
df['my_earnings_usd'] = df['my_earnings_usd'].fillna(0.00)

/var/folders/bd/pl944hbj61n6mpghlwvnxy5r0000gn/T/ipykernel_6501/2499682987.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['my_earnings_usd'] = df['my_earnings_usd'].fillna(0.00)

In [17]:
df

,song_title,my_earnings_usd,song_id,writers
0,+5,7.96,6565950,"Amiranovich Amiranovich(50%), Leonardo Bostan(..."
1,1 XANNY GEHT NOCH KLAR,2.26,6547320,"Kewin Rewers(50%), Leonardo Bostan(50%)"
2,2 COCKY,0.00,5992541,"Leonardo Bostan(50%), Luis Gaerdes(50%)"
3,??????,0.04,6572314,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost..."
4,AGAIN,132.90,6537410,"Jairmy Long(50%), Leonardo Bostan(12.50%), Max..."
...,...,...,...,...
123,WHO IS MELO?,72.52,6547321,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost..."
124,WTF I WANT,89.47,6972662,"Leonardo Bostan(12.50%), Martin Mccurtis(25%),..."
125,WUSYANAME,157.47,6685283,"Klayd Klayd(30%), Leonardo Bostan(70%)"
126,ZA SMOKIN,0.00,6207402,"Angelo Turpin Jr(50%), Leonardo Bostan(50%)"
127,ZOR DEIL,0.59,7172291,"Alp Mutlu(16.60%), Emir Oztaskin(16.70%), Ferh..."

In [18]:
import re

def extract_my_share(writers_string):
    match = re.search(r'Leonardo Bostan\((\d+\.?\d*)%\)', str(writers_string))
    if match:
        return float(match.group(1))
    return None

def extract_n_collaborators(writers_string):
    return str(writers_string).count('(')

In [19]:
df['my_share_pct'] = df['writers'].apply(extract_my_share)

In [20]:
df

,song_title,my_earnings_usd,song_id,writers,my_share_pct
0,+5,7.96,6565950,"Amiranovich Amiranovich(50%), Leonardo Bostan(...",50.0
1,1 XANNY GEHT NOCH KLAR,2.26,6547320,"Kewin Rewers(50%), Leonardo Bostan(50%)",50.0
2,2 COCKY,0.00,5992541,"Leonardo Bostan(50%), Luis Gaerdes(50%)",50.0
3,??????,0.04,6572314,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost...",25.0
4,AGAIN,132.90,6537410,"Jairmy Long(50%), Leonardo Bostan(12.50%), Max...",12.5
...,...,...,...,...,...
123,WHO IS MELO?,72.52,6547321,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost...",25.0
124,WTF I WANT,89.47,6972662,"Leonardo Bostan(12.50%), Martin Mccurtis(25%),...",12.5
125,WUSYANAME,157.47,6685283,"Klayd Klayd(30%), Leonardo Bostan(70%)",70.0
126,ZA SMOKIN,0.00,6207402,"Angelo Turpin Jr(50%), Leonardo Bostan(50%)",50.0
127,ZOR DEIL,0.59,7172291,"Alp Mutlu(16.60%), Emir Oztaskin(16.70%), Ferh...",16.7

In [21]:
df['collaboratos_count'] = df['writers'].apply(extract_n_collaborators)

In [22]:
df

,song_title,my_earnings_usd,song_id,writers,my_share_pct,collaboratos_count
0,+5,7.96,6565950,"Amiranovich Amiranovich(50%), Leonardo Bostan(...",50.0,2
1,1 XANNY GEHT NOCH KLAR,2.26,6547320,"Kewin Rewers(50%), Leonardo Bostan(50%)",50.0,2
2,2 COCKY,0.00,5992541,"Leonardo Bostan(50%), Luis Gaerdes(50%)",50.0,2
3,??????,0.04,6572314,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost...",25.0,3
4,AGAIN,132.90,6537410,"Jairmy Long(50%), Leonardo Bostan(12.50%), Max...",12.5,4
...,...,...,...,...,...,...
123,WHO IS MELO?,72.52,6547321,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost...",25.0,3
124,WTF I WANT,89.47,6972662,"Leonardo Bostan(12.50%), Martin Mccurtis(25%),...",12.5,4
125,WUSYANAME,157.47,6685283,"Klayd Klayd(30%), Leonardo Bostan(70%)",70.0,2
126,ZA SMOKIN,0.00,6207402,"Angelo Turpin Jr(50%), Leonardo Bostan(50%)",50.0,2
127,ZOR DEIL,0.59,7172291,"Alp Mutlu(16.60%), Emir Oztaskin(16.70%), Ferh...",16.7,4

In [23]:
df = df.rename(columns={'collaboratos_count': 'collaborators_count'})

In [24]:
df

,song_title,my_earnings_usd,song_id,writers,my_share_pct,collaborators_count
0,+5,7.96,6565950,"Amiranovich Amiranovich(50%), Leonardo Bostan(...",50.0,2
1,1 XANNY GEHT NOCH KLAR,2.26,6547320,"Kewin Rewers(50%), Leonardo Bostan(50%)",50.0,2
2,2 COCKY,0.00,5992541,"Leonardo Bostan(50%), Luis Gaerdes(50%)",50.0,2
3,??????,0.04,6572314,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost...",25.0,3
4,AGAIN,132.90,6537410,"Jairmy Long(50%), Leonardo Bostan(12.50%), Max...",12.5,4
...,...,...,...,...,...,...
123,WHO IS MELO?,72.52,6547321,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost...",25.0,3
124,WTF I WANT,89.47,6972662,"Leonardo Bostan(12.50%), Martin Mccurtis(25%),...",12.5,4
125,WUSYANAME,157.47,6685283,"Klayd Klayd(30%), Leonardo Bostan(70%)",70.0,2
126,ZA SMOKIN,0.00,6207402,"Angelo Turpin Jr(50%), Leonardo Bostan(50%)",50.0,2
127,ZOR DEIL,0.59,7172291,"Alp Mutlu(16.60%), Emir Oztaskin(16.70%), Ferh...",16.7,4

In [25]:
df['my_share_pct'].isna().sum()

np.int64(0)

In [26]:
df['true_song_size'] = df['my_earnings_usd'] / (df['my_share_pct'] / 100)

In [27]:
df

,song_title,my_earnings_usd,song_id,writers,my_share_pct,collaborators_count,true_song_size
0,+5,7.96,6565950,"Amiranovich Amiranovich(50%), Leonardo Bostan(...",50.0,2,15.920000
1,1 XANNY GEHT NOCH KLAR,2.26,6547320,"Kewin Rewers(50%), Leonardo Bostan(50%)",50.0,2,4.520000
2,2 COCKY,0.00,5992541,"Leonardo Bostan(50%), Luis Gaerdes(50%)",50.0,2,0.000000
3,??????,0.04,6572314,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost...",25.0,3,0.160000
4,AGAIN,132.90,6537410,"Jairmy Long(50%), Leonardo Bostan(12.50%), Max...",12.5,4,1063.200000
...,...,...,...,...,...,...,...
123,WHO IS MELO?,72.52,6547321,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost...",25.0,3,290.080000
124,WTF I WANT,89.47,6972662,"Leonardo Bostan(12.50%), Martin Mccurtis(25%),...",12.5,4,715.760000
125,WUSYANAME,157.47,6685283,"Klayd Klayd(30%), Leonardo Bostan(70%)",70.0,2,224.957143
126,ZA SMOKIN,0.00,6207402,"Angelo Turpin Jr(50%), Leonardo Bostan(50%)",50.0,2,0.000000
127,ZOR DEIL,0.59,7172291,"Alp Mutlu(16.60%), Emir Oztaskin(16.70%), Ferh...",16.7,4,3.532934

In [28]:
pd.set_option('display.float_format', '{:.2f}'.format)

In [29]:
df

,song_title,my_earnings_usd,song_id,writers,my_share_pct,collaborators_count,true_song_size
0,+5,7.96,6565950,"Amiranovich Amiranovich(50%), Leonardo Bostan(...",50.00,2,15.92
1,1 XANNY GEHT NOCH KLAR,2.26,6547320,"Kewin Rewers(50%), Leonardo Bostan(50%)",50.00,2,4.52
2,2 COCKY,0.00,5992541,"Leonardo Bostan(50%), Luis Gaerdes(50%)",50.00,2,0.00
3,??????,0.04,6572314,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost...",25.00,3,0.16
4,AGAIN,132.90,6537410,"Jairmy Long(50%), Leonardo Bostan(12.50%), Max...",12.50,4,1063.20
...,...,...,...,...,...,...,...
123,WHO IS MELO?,72.52,6547321,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost...",25.00,3,290.08
124,WTF I WANT,89.47,6972662,"Leonardo Bostan(12.50%), Martin Mccurtis(25%),...",12.50,4,715.76
125,WUSYANAME,157.47,6685283,"Klayd Klayd(30%), Leonardo Bostan(70%)",70.00,2,224.96
126,ZA SMOKIN,0.00,6207402,"Angelo Turpin Jr(50%), Leonardo Bostan(50%)",50.00,2,0.00
127,ZOR DEIL,0.59,7172291,"Alp Mutlu(16.60%), Emir Oztaskin(16.70%), Ferh...",16.70,4,3.53

In [30]:
median_true_song_size = df['true_song_size'].median()

In [31]:
median_true_song_size

np.float64(97.63)

In [32]:
df['is_large_song'] = df['true_song_size'] > median_true_song_size

In [33]:
df

,song_title,my_earnings_usd,song_id,writers,my_share_pct,collaborators_count,true_song_size,is_large_song
0,+5,7.96,6565950,"Amiranovich Amiranovich(50%), Leonardo Bostan(...",50.00,2,15.92,False
1,1 XANNY GEHT NOCH KLAR,2.26,6547320,"Kewin Rewers(50%), Leonardo Bostan(50%)",50.00,2,4.52,False
2,2 COCKY,0.00,5992541,"Leonardo Bostan(50%), Luis Gaerdes(50%)",50.00,2,0.00,False
3,??????,0.04,6572314,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost...",25.00,3,0.16,False
4,AGAIN,132.90,6537410,"Jairmy Long(50%), Leonardo Bostan(12.50%), Max...",12.50,4,1063.20,True
...,...,...,...,...,...,...,...,...
123,WHO IS MELO?,72.52,6547321,"Drugankin Ivan Dmitrievich(25%), Leonardo Bost...",25.00,3,290.08,True
124,WTF I WANT,89.47,6972662,"Leonardo Bostan(12.50%), Martin Mccurtis(25%),...",12.50,4,715.76,True
125,WUSYANAME,157.47,6685283,"Klayd Klayd(30%), Leonardo Bostan(70%)",70.00,2,224.96,True
126,ZA SMOKIN,0.00,6207402,"Angelo Turpin Jr(50%), Leonardo Bostan(50%)",50.00,2,0.00,False
127,ZOR DEIL,0.59,7172291,"Alp Mutlu(16.60%), Emir Oztaskin(16.70%), Ferh...",16.70,4,3.53,False

In [34]:
df['my_earnings_usd'].sum()

np.float64(41807.62000000001)

In [35]:
df['is_large_song'].value.counts()

AttributeError: 'Series' object has no attribute 'value'

In [36]:
df['is_large_song'].value_counts()

is_large_song
False    64
True     64
Name: count, dtype: int64

In [37]:
df.to_csv('.../data/processed/analysis_ready.csv',index=False)

OSError: Cannot save file into a non-existent directory: '.../data/processed'

In [37]:
df.to_csv('.../data/processed/analysis_ready.csv',index=False)

OSError: Cannot save file into a non-existent directory: '.../data/processed'

In [38]:
df.to_csv('../data/processed/analysis_ready.csv',index=False)